
npmRegistries:
  "https://npm.greenfinity.hu":
    npmAlwaysAuth: false

npmScopes:
  rescript-logger:
    npmPublishRegistry: "https://npm.greenfinity.hu"
    npmRegistryServer: "https://npm.greenfinity.hu"
